// This file is part of midnightntwrk/example-counter.
// Copyright (C) 2025 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
 * This file is the main driver for the Midnight ballot example.
 * The entry point is the run function, at the end of the file.
 * We expect the startup files (testnet-remote.ts, standalone.ts, etc.) to
 * call run with some specific configuration that sets the network addresses
 * of the servers this file relies on.
 */

// Wallet seed: 8dd96c613b92a1ced03ac5e71a039d4447cfe84928864fc38260b28cd30378c2

import { createInterface, type Interface } from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import { WebSocket } from 'ws';
// import { webcrypto } from 'crypto';
import {
    type BallotProviders,
    BallotAPI,
    utils,
    type BallotDerivedState,
    type DeployedBallotContract,
    type PrivateStateId,
    ballotPrivateStateKey,
} from '../../ballot-api/src/index';
import { ledger, type Ledger, PollState } from '../../contract/src/managed/ballot/contract/index.cjs';
import {
    type BalancedTransaction,
    createBalancedTx,
    type MidnightProvider,
    type UnbalancedTransaction,
    type WalletProvider,
} from '@midnight-ntwrk/midnight-js-types';
import { type Wallet } from '@midnight-ntwrk/wallet-api';
import * as Rx from 'rxjs';
import { type CoinInfo, nativeToken, Transaction, type TransactionId } from '@midnight-ntwrk/ledger';
import { Transaction as ZswapTransaction } from '@midnight-ntwrk/zswap';
import { NodeZkConfigProvider } from '@midnight-ntwrk/midnight-js-node-zk-config-provider';
import { type Resource, WalletBuilder } from '@midnight-ntwrk/wallet';
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { httpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { type Logger } from 'pino';
import { type Config, StandaloneConfig } from './config.js';
import type { StartedDockerComposeEnvironment, DockerComposeEnvironment } from 'testcontainers';
import { levelPrivateStateProvider } from '@midnight-ntwrk/midnight-js-level-private-state-provider';
import { type ContractAddress } from '@midnight-ntwrk/compact-runtime';
import { toHex, assertIsContractAddress } from '@midnight-ntwrk/midnight-js-utils';
import { getLedgerNetworkId, getZswapNetworkId } from '@midnight-ntwrk/midnight-js-network-id';

// @ts-expect-error: It's needed to enable WebSocket usage through apollo
globalThis.WebSocket = WebSocket;

/* **********************************************************************
 * getBallotLedgerState: a helper that queries the current state of
 * the data on the ledger, for a specific ballot contract.
 * Note that the Ledger type returned here is not some generic,
 * abstract ledger object, but specifically the type generated by
 * the Compact compiler to correspond to the ledger declaration
 * in the ballot contract.
 */

export const getBallotLedgerState = async (
    providers: BallotProviders,
    contractAddress: ContractAddress,
): Promise<Ledger | null> => {
    assertIsContractAddress(contractAddress);
    const contractState = await providers.publicDataProvider.queryContractState(contractAddress);
    return contractState != null ? ledger(contractState.data) : null;
};

/* **********************************************************************
 * deployOrJoin: returns a contract, by prompting the user about
 * whether to deploy a new one or join an existing one and then
 * calling the appropriate helper.
 */

const DEPLOY_OR_JOIN_QUESTION = `
You can do one of the following:
  1. Deploy a new ballot contract
  2. Join an existing ballot contract
  3. Exit
Which would you like to do? `;

const deployOrJoin = async (providers: BallotProviders, rli: Interface, logger: Logger): Promise<BallotAPI | null> => {
    let api: BallotAPI | null = null;

    while (true) {
        const choice = await rli.question(DEPLOY_OR_JOIN_QUESTION);
        switch (choice) {
            case '1':
                api = await BallotAPI.deploy(providers, logger);
                logger.info(`Deployed contract at address: ${api.deployedContractAddress}`);
                return api;
            case '2':
                api = await BallotAPI.join(providers, await rli.question('What is the contract address (in hex)? '), logger);
                logger.info(`Joined contract at address: ${api.deployedContractAddress}`);
                return api;
            case '3':
                logger.info('Exiting...');
                return null;
            default:
                logger.error(`Invalid choice: ${choice}`);
        }
    }
};

/* **********************************************************************
 * displayLedgerState: shows the values of each of the fields declared
 * by the contract to be in the ledger state of the ballot.
 */

const displayLedgerState = async (
    providers: BallotProviders,
    deployedBallotContract: DeployedBallotContract,
    logger: Logger,
): Promise<void> => {
    const contractAddress = deployedBallotContract.deployTxData.public.contractAddress;
    const ledgerState = await getBallotLedgerState(providers, contractAddress);
    if (ledgerState === null) {
        logger.info(`There is no ballot contract deployed at ${contractAddress}`);
    } else {
        const pollState =
            ledgerState.pollState === PollState.OPEN
                ? 'open'
                : ledgerState.pollState === PollState.CLOSED
                    ? 'closed'
                    : 'empty';
        const latestQuestion = !ledgerState.question.is_some ? 'none' : ledgerState.question.value;
        logger.info(`Current poll state is: '${pollState}'`);
        logger.info(`Current question is: '${latestQuestion}'`);
        logger.info(`Current yes count is: ${ledgerState.yesCount}`);
        logger.info(`Current no count is: ${ledgerState.noCount}`);
        logger.info(`Current sequence is: ${ledgerState.sequence}`);
        logger.info(`Current poll owner is: '${toHex(ledgerState.pollOwner)}'`);
    }
};

/* **********************************************************************
 * displayPrivateState: shows the hex-formatted value of the secret key.
 */

const displayPrivateState = async (providers: BallotProviders, logger: Logger): Promise<void> => {
    const privateState = await providers.privateStateProvider.get(ballotPrivateStateKey);
    if (privateState === null) {
        logger.info(`There is no existing ballot private state`);
    } else {
        logger.info(`Current secret key is: ${toHex(privateState.secretKey)}`);
    }
};

/* **********************************************************************
 * displayDerivedState: shows the values of derived state which is made
 * by combining the ledger state with private state. In this example, the
 * derived state compares the poll owner's key with the private secret key to
 * determine if the current user is the poll owner.
 */

const displayDerivedState = (ledgerState: BallotDerivedState | undefined, logger: Logger) => {
    if (ledgerState === undefined) {
        logger.info(`No ballot state currently available`);
    } else {
        const pollState =
            ledgerState.pollState === PollState.OPEN
                ? 'open'
                : ledgerState.pollState === PollState.CLOSED
                    ? 'closed'
                    : 'empty';
        const latestQuestion = ledgerState.question ?? 'none';
        logger.info(`Current poll state is: '${pollState}'`);
        logger.info(`Current question is: '${latestQuestion}'`);
        logger.info(`Current yes count is: ${ledgerState.yesCount}`);
        logger.info(`Current no count is: ${ledgerState.noCount}`);
        logger.info(`Current sequence is: ${ledgerState.sequence}`);
        logger.info(`Current poll owner is: '${ledgerState.isOwner ? 'you' : 'not you'}'`);
    }
};

/* **********************************************************************
 * mainLoop: the main interactive menu of the ballot CLI.
 * Before starting the loop, the user is prompted to deploy a new
 * contract or join an existing one.
 */

const MAIN_LOOP_QUESTION = `
You can do one of the following:
  1. Open a new poll
  2. Vote "Yes"
  3. Vote "No"
  4. Close the poll
  5. Display the current ledger state (known by everyone)
  6. Display the current private state (known only to this DApp instance)
  7. Display the current derived state (known only to this DApp instance)
  8. Exit
Which would you like to do? `;

const mainLoop = async (providers: BallotProviders, rli: Interface, logger: Logger): Promise<void> => {
    const ballotApi = await deployOrJoin(providers, rli, logger);
    if (ballotApi === null) {
        return;
    }
    let currentState: BallotDerivedState | undefined;
    const stateObserver = {
        next: (state: BallotDerivedState) => (currentState = state),
    };
    const subscription = ballotApi.state$.subscribe(stateObserver);
    try {
        while (true) {
            const choice = await rli.question(MAIN_LOOP_QUESTION);
            switch (choice) {
                case '1': {
                    const question = await rli.question(`What question do you want to open the poll with? `);
                    await ballotApi.openPoll(question);
                    break;
                }
                case '2':
                    await ballotApi.voteYes();
                    break;
                case '3':
                    await ballotApi.voteNo();
                    break;
                case '4':
                    await ballotApi.closePoll();
                    break;
                case '5':
                    await displayLedgerState(providers, ballotApi.deployedContract, logger);
                    break;
                case '6':
                    await displayPrivateState(providers, logger);
                    break;
                case '7':
                    displayDerivedState(currentState, logger);
                    break;
                case '8':
                    logger.info('Exiting...');
                    return;
                default:
                    logger.error(`Invalid choice: ${choice}`);
            }
        }
    } finally {
        // While we allow errors to bubble up to the 'run' function, we will always need to dispose of the state
        // subscription when we exit.
        subscription.unsubscribe();
    }
};

/* **********************************************************************
 * createWalletAndMidnightProvider: returns an object that
 * satifies both the WalletProvider and MidnightProvider
 * interfaces, both implemented in terms of the given wallet.
 */

const createWalletAndMidnightProvider = async (wallet: Wallet): Promise<WalletProvider & MidnightProvider> => {
    const state = await Rx.firstValueFrom(wallet.state());
    return {
        coinPublicKey: state.coinPublicKey,
        encryptionPublicKey: state.encryptionPublicKey,
        balanceTx(tx: UnbalancedTransaction, newCoins: CoinInfo[]): Promise<BalancedTransaction> {
            return wallet
                .balanceTransaction(
                    ZswapTransaction.deserialize(tx.serialize(getLedgerNetworkId()), getZswapNetworkId()),
                    newCoins,
                )
                .then((tx) => wallet.proveTransaction(tx))
                .then((zswapTx) => Transaction.deserialize(zswapTx.serialize(getZswapNetworkId()), getLedgerNetworkId()))
                .then(createBalancedTx);
        },
        submitTx(tx: BalancedTransaction): Promise<TransactionId> {
            return wallet.submitTransaction(tx);
        },
    };
};

/* **********************************************************************
 * waitForFunds: wait for tokens to appear in a wallet.
 *
 * This is an interesting example of watching the stream of states
 * coming from the pub-sub indexer.  It watches both
 *  1. how close the state is to present reality and
 *  2. the balance held by the wallet.
 */

const waitForFunds = (wallet: Wallet, logger: Logger) =>
    Rx.firstValueFrom(
        wallet.state().pipe(
            Rx.throttleTime(10_000),
            Rx.tap((state) => {
                const scanned = state.syncProgress?.synced ?? 0n;
                const behind = state.syncProgress?.lag.applyGap.toString() ?? 'unknown number';
                logger.info(`Wallet processed ${scanned} indices, remaining ${behind}`);
            }),
            Rx.filter((state) => {
                // Let's allow progress only if wallet is close enough
                const synced = typeof state.syncProgress?.synced === 'bigint' ? state.syncProgress.synced : 0n;
                const total = typeof state.syncProgress?.lag?.applyGap === 'bigint' ? state.syncProgress.lag.applyGap : 1_000n;
                return total - synced < 100n;
            }),
            Rx.map((s) => s.balances[nativeToken()] ?? 0n),
            Rx.filter((balance) => balance > 0n),
        ),
    );

/* **********************************************************************
 * buildWalletAndWaitForFunds: the main function that creates a wallet
 * and waits for tokens to appear in it.  The various "buildWallet"
 * functions all arrive here after collecting information for the
 * arguments.
 */

const buildWalletAndWaitForFunds = async (
    { indexer, indexerWS, node, proofServer }: Config,
    logger: Logger,
    seed: string,
): Promise<Wallet & Resource> => {
    const wallet = await WalletBuilder.buildFromSeed(
        indexer,
        indexerWS,
        proofServer,
        node,
        seed,
        getZswapNetworkId(),
        'warn',
    );
    wallet.start();
    const state = await Rx.firstValueFrom(wallet.state());
    logger.info(`Your wallet seed is: ${seed}`);
    logger.info(`Your wallet address is: ${state.address}`);
    let balance = state.balances[nativeToken()];
    if (balance === undefined || balance === 0n) {
        logger.info(`Your wallet balance is: 0`);
        logger.info(`Waiting to receive tokens...`);
        balance = await waitForFunds(wallet, logger);
    }
    logger.info(`Your wallet balance is: ${balance}`);
    return wallet;
};

// Generate a random see and create the wallet with that.
const buildFreshWallet = async (config: Config, logger: Logger): Promise<Wallet & Resource> =>
    await buildWalletAndWaitForFunds(config, logger, toHex(utils.randomBytes(32)));

// Prompt for a seed and create the wallet with that.
const buildWalletFromSeed = async (config: Config, rli: Interface, logger: Logger): Promise<Wallet & Resource> => {
    const seed = await rli.question('Enter your wallet seed: ');
    return await buildWalletAndWaitForFunds(config, logger, seed);
};

/* ***********************************************************************
 * This seed gives access to tokens minted in the genesis block of a local development node - only
 * used in standalone networks to build a wallet with initial funds.
 */
const GENESIS_MINT_WALLET_SEED = '0000000000000000000000000000000000000000000000000000000000000001';

/* **********************************************************************
 * buildWallet: unless running in a standalone (offline) mode,
 * prompt the user to tell us whether to create a new wallet
 * or recreate one from a prior seed.
 */

const WALLET_LOOP_QUESTION = `
You can do one of the following:
  1. Build a fresh wallet
  2. Build wallet from a seed
  3. Exit
Which would you like to do? `;

const buildWallet = async (config: Config, rli: Interface, logger: Logger): Promise<(Wallet & Resource) | null> => {
    if (config instanceof StandaloneConfig) {
        return await buildWalletAndWaitForFunds(config, logger, GENESIS_MINT_WALLET_SEED);
    }
    while (true) {
        const choice = await rli.question(WALLET_LOOP_QUESTION);
        switch (choice) {
            case '1':
                return await buildFreshWallet(config, logger);
            case '2':
                return await buildWalletFromSeed(config, rli, logger);
            case '3':
                logger.info('Exiting...');
                return null;
            default:
                logger.error(`Invalid choice: ${choice}`);
        }
    }
};

const mapContainerPort = (env: StartedDockerComposeEnvironment, url: string, containerName: string) => {
    const mappedUrl = new URL(url);
    const container = env.getContainer(containerName);

    mappedUrl.port = String(container.getFirstMappedPort());

    return mappedUrl.toString().replace(/\/+$/, '');
};

/* **********************************************************************
 * run: the main entry point that starts the whole ballot CLI.
 *
 * If called with a Docker environment argument, the application
 * will wait for Docker to be ready before doing anything else.
 */

export const run = async (config: Config, logger: Logger, dockerEnv?: DockerComposeEnvironment): Promise<void> => {
    const rli = createInterface({ input, output, terminal: true });
    let env;
    if (dockerEnv !== undefined) {
        env = await dockerEnv.up();

        if (config instanceof StandaloneConfig) {
            config.indexer = mapContainerPort(env, config.indexer, 'ballot-indexer');
            config.indexerWS = mapContainerPort(env, config.indexerWS, 'ballot-indexer');
            config.node = mapContainerPort(env, config.node, 'ballot-node');
            config.proofServer = mapContainerPort(env, config.proofServer, 'ballot-proof-server');
        }
    }
    const wallet = await buildWallet(config, rli, logger);
    try {
        if (wallet !== null) {
            const walletAndMidnightProvider = await createWalletAndMidnightProvider(wallet);
            const providers = {
                privateStateProvider: levelPrivateStateProvider<PrivateStateId>({
                    privateStateStoreName: config.privateStateStoreName,
                }),
                publicDataProvider: indexerPublicDataProvider(config.indexer, config.indexerWS),
                zkConfigProvider: new NodeZkConfigProvider<'openPoll' | 'voteYes' | 'voteNo' | 'closePoll'>(config.zkConfigPath),
                proofProvider: httpClientProofProvider(config.proofServer),
                walletProvider: walletAndMidnightProvider,
                midnightProvider: walletAndMidnightProvider,
            };
            await mainLoop(providers, rli, logger);
        }
    } catch (e) {
        logError(logger, e);
        logger.info('Exiting...');
    } finally {
        try {
            rli.close();
            rli.removeAllListeners();
        } catch (e) {
            logError(logger, e);
        } finally {
            try {
                if (wallet !== null) {
                    await wallet.close();
                }
            } catch (e) {
                logError(logger, e);
            } finally {
                try {
                    if (env !== undefined) {
                        await env.down();
                        logger.info('Goodbye');
                        process.exit(0);
                    }
                } catch (e) {
                    logError(logger, e);
                }
            }
        }
    }
};

function logError(logger: Logger, e: unknown) {
    if (e instanceof Error) {
        logger.error(`Found error '${e.message}'`);
        logger.debug(`${e.stack}`);
    } else {
        logger.error(`Found error (unknown type)`);
    }
}
